package database

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/joho/godotenv"
)

// ============================================================
// 1. CONNECT TO POSTGRESQL
// This function connects Agro-Shield to the PostgreSQL database.
// ============================================================

func ConnectDB() (*sql.DB, error) {
	godotenv.Load()

	databaseURL := os.Getenv("DATABASE_URL")

	if databaseURL == "" {
		return nil, fmt.Errorf("DATABASE_URL is not set")
	}

	db, err := sql.Open("pgx", databaseURL)
	if err != nil {
		return nil, err
	}

	if err := db.Ping(); err != nil {
		return nil, err
	}

	log.Println("✅ Connected to PostgreSQL database")

	return db, nil
}

// ============================================================
// 2. RUN DATABASE MIGRATIONS
// This function creates Agro-Shield's database tables.
// ============================================================

func RunMigration(db *sql.DB) error {

	// ========================================================
	// 3. FARMERS TABLE
	// Stores farmer account information.
	// ========================================================

	farmersTable := `
		CREATE TABLE IF NOT EXISTS farmers (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			full_name TEXT NOT NULL,
			phone TEXT NOT NULL UNIQUE,
			email TEXT,
			password_hash TEXT NOT NULL,
			location TEXT NOT NULL,
			role TEXT NOT NULL DEFAULT 'farmer',
			photo_url TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`

	_, err := db.Exec(farmersTable)
	if err != nil {
		return err
	}

	log.Println("✅ Farmers table migrated successfully")

	// ========================================================
	// 4. EMAIL COLUMN MIGRATION
	// Adds email to an existing farmers table.
	//
	// CREATE TABLE IF NOT EXISTS does NOT modify a table
	// that already exists.
	//
	// This ALTER TABLE makes sure old databases also get
	// the new email column.
	// ========================================================

	addEmailColumn := `
		ALTER TABLE farmers
		ADD COLUMN IF NOT EXISTS email TEXT;
	`

	_, err = db.Exec(addEmailColumn)
	if err != nil {
		return err
	}

	log.Println("✅ Farmers email column migrated successfully")

	// ========================================================
	// 5. CROPS TABLE
	// Stores crops added by farmers for sale.
	// ========================================================

	cropsTable := `
		CREATE TABLE IF NOT EXISTS crops (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			farmer_id INTEGER NOT NULL,
			name TEXT NOT NULL,
			quantity DOUBLE PRECISION NOT NULL,
			unit TEXT NOT NULL,
			location TEXT NOT NULL,
			price_per_unit DOUBLE PRECISION NOT NULL,
			listed_for_sale BOOLEAN NOT NULL DEFAULT FALSE,
			image_url TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

			CONSTRAINT fk_crops_farmer
				FOREIGN KEY (farmer_id)
				REFERENCES farmers(id)
				ON DELETE CASCADE
		);
	`

	_, err = db.Exec(cropsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Crops table migrated successfully")

	// ========================================================
	// 6. DIAGNOSES TABLE
	// Stores AI diagnosis results.
	// ========================================================

	diagnosesTable := `
		CREATE TABLE IF NOT EXISTS diagnoses (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		farmer_id INTEGER NOT NULL,
		image_name TEXT NOT NULL,
		result TEXT NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_diagnoses_farmer
			FOREIGN KEY (farmer_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(diagnosesTable)
	if err != nil {
		return err
	}

	log.Println("✅ Diagnoses table migrated successfully")

	// ========================================================
	// 7. DIAGNOSIS MEDIA TABLE
	// Stores images, audio, and video connected to diagnoses.
	// ========================================================

	diagnosisMediaTable := `
	CREATE TABLE IF NOT EXISTS diagnosis_media (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		diagnosis_id INTEGER NOT NULL,
		media_type TEXT NOT NULL,
		file_name TEXT NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_diagnosis_media_diagnosis
			FOREIGN KEY (diagnosis_id)
			REFERENCES diagnoses(id)
			ON DELETE CASCADE
	);
	`

	_, err = db.Exec(diagnosisMediaTable)
	if err != nil {
		return err
	}

	log.Println("✅ Diagnosis media table migrated successfully")

	// ========================================================
	// 8. ORDERS TABLE
	// Stores purchases made by buyers.
	// ========================================================

	ordersTable := `
	CREATE TABLE IF NOT EXISTS orders (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		buyer_id INTEGER NOT NULL,
		crop_id INTEGER NOT NULL,
		quantity DOUBLE PRECISION NOT NULL,
		total_price DOUBLE PRECISION NOT NULL,
		status TEXT NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_orders_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_orders_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id)
	);
	`

	_, err = db.Exec(ordersTable)
	if err != nil {
		return err
	}

	log.Println("✅ Orders table migrated successfully")

	// ========================================================
	// 9. NEGOTIATIONS TABLE
	// Stores buyer and farmer price negotiations.
	// ========================================================

	negotiationsTable := `
	CREATE TABLE IF NOT EXISTS negotiations (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		crop_id INTEGER NOT NULL,
		buyer_id INTEGER NOT NULL,
		farmer_id INTEGER NOT NULL,
		quantity DOUBLE PRECISION NOT NULL,
		status TEXT NOT NULL,
		round_count INTEGER NOT NULL DEFAULT 0,
		max_rounds INTEGER NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		expires_at TIMESTAMP,

		CONSTRAINT fk_negotiations_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id),

		CONSTRAINT fk_negotiations_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_negotiations_farmer
			FOREIGN KEY (farmer_id)
			REFERENCES farmers(id)
	);
	`

	_, err = db.Exec(negotiationsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiations table migrated successfully")

	// ========================================================
	// 10. NEGOTIATION MESSAGES TABLE
	// Stores messages and offers inside negotiations.
	// ========================================================

	// ========================================================
// 10. NEGOTIATION MESSAGES TABLE
// Stores messages and individual offers inside negotiations.
//
// IMPORTANT:
// - The negotiation remains open when an offer is rejected.
// - Each offer has its own status.
// - Accepted/rejected applies to the individual offer,
//   not the entire conversation.
// ========================================================

negotiationMessagesTable := `
	CREATE TABLE IF NOT EXISTS negotiation_messages (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		negotiation_id INTEGER NOT NULL,
		sender_id INTEGER NOT NULL,
		offer_price DOUBLE PRECISION NOT NULL,
		message TEXT NOT NULL,
		offer_status TEXT NOT NULL DEFAULT 'pending',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_messages_negotiation
			FOREIGN KEY (negotiation_id)
			REFERENCES negotiations(id)
			ON DELETE CASCADE,

		CONSTRAINT fk_messages_sender
			FOREIGN KEY (sender_id)
			REFERENCES farmers(id)
	);
`

_, err = db.Exec(negotiationMessagesTable)
if err != nil {
	return err
}

log.Println("✅ Negotiation messages table migrated successfully")

// ========================================================
// 10B. OFFER STATUS MIGRATION
// Adds offer_status to existing negotiation_messages tables.
//
// CREATE TABLE IF NOT EXISTS does not modify an existing
// table, so this migration is required for old databases.
// ========================================================

addOfferStatusColumn := `
	ALTER TABLE negotiation_messages
	ADD COLUMN IF NOT EXISTS offer_status TEXT NOT NULL DEFAULT 'pending';
`

_, err = db.Exec(addOfferStatusColumn)
if err != nil {
	return err
}

log.Println("✅ Negotiation offer status column migrated successfully")
	// ========================================================
	// 11. CART ITEMS TABLE
	// Stores products that have been accepted through negotiation
	// and are waiting for checkout.
	// ========================================================

	cartItemsTable := `
	CREATE TABLE IF NOT EXISTS cart_items (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		buyer_id INTEGER NOT NULL,

		crop_id INTEGER NOT NULL,

		negotiation_id INTEGER NOT NULL,

		quantity DOUBLE PRECISION NOT NULL,

		price_per_unit DOUBLE PRECISION NOT NULL,

		total_price DOUBLE PRECISION NOT NULL,

		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_cart_items_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_cart_items_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id),

		CONSTRAINT fk_cart_items_negotiation
			FOREIGN KEY (negotiation_id)
			REFERENCES negotiations(id)
			ON DELETE CASCADE,

		CONSTRAINT chk_cart_items_quantity
			CHECK (quantity > 0),

		CONSTRAINT chk_cart_items_price
			CHECK (price_per_unit > 0),

		CONSTRAINT chk_cart_items_total
			CHECK (total_price > 0)
	);
	`

	_, err = db.Exec(cartItemsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Cart items table migrated successfully")
	// ========================================================
	// 12. MIGRATION COMPLETE
	// ========================================================

	log.Println("✅ All database migrations completed successfully")

	return nil
}
