package database

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/joho/godotenv"
)

func ConnectDB() (*sql.DB, error) {
	godotenv.Load()
	databaseURL := os.Getenv("DATABASE_URL")

	if databaseURL == "" {
		return nil, fmt.Errorf("DATABASE_URL is not set")
	}

	db, err := sql.Open("pgx", databaseURL)
	if err != nil {
		return nil, err
	}

	if err := db.Ping(); err != nil {
		return nil, err
	}

	log.Println("✅ Connected to PostgreSQL database")

	return db, nil
}

func RunMigration(db *sql.DB) error {
	farmersTable := `
		CREATE TABLE IF NOT EXISTS farmers (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			full_name TEXT NOT NULL,
			phone TEXT NOT NULL UNIQUE,
			password_hash TEXT NOT NULL,
			location TEXT NOT NULL,
			role TEXT NOT NULL DEFAULT 'farmer',
			photo_url TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`

	_, err := db.Exec(farmersTable)
	if err != nil {
		return err
	}

	log.Println("✅ Farmers table migrated successfully")

	// 👇 ADD THE CROPS MIGRATION HERE
	cropsTable := `
		CREATE TABLE IF NOT EXISTS crops (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			farmer_id INTEGER NOT NULL,
			name TEXT NOT NULL,
			quantity DOUBLE PRECISION NOT NULL,
			unit TEXT NOT NULL,
			location TEXT NOT NULL,
			price_per_unit DOUBLE PRECISION NOT NULL,
			listed_for_sale BOOLEAN NOT NULL DEFAULT FALSE,
			image_url TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

			CONSTRAINT fk_crops_farmer
				FOREIGN KEY (farmer_id)
				REFERENCES farmers(id)
				ON DELETE CASCADE
		);
	`

	_, err = db.Exec(cropsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Crops table migrated successfully")
	diagnosesTable := `
	CREATE TABLE IF NOT EXISTS diagnoses (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		farmer_id INTEGER NOT NULL,
		image_name TEXT NOT NULL,
		result TEXT NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_diagnoses_farmer
			FOREIGN KEY (farmer_id)
			REFERENCES farmers(id)
			ON DELETE CASCADE
	);
`

	_, err = db.Exec(diagnosesTable)
	if err != nil {
		return err
	}

	log.Println("✅ Diagnoses table migrated successfully")
	ordersTable := `
	CREATE TABLE IF NOT EXISTS orders (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		buyer_id INTEGER NOT NULL,
		crop_id INTEGER NOT NULL,
		quantity DOUBLE PRECISION NOT NULL,
		total_price DOUBLE PRECISION NOT NULL,
		status TEXT NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_orders_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_orders_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id)
	);
`

	_, err = db.Exec(ordersTable)
	if err != nil {
		return err
	}

	log.Println("✅ Orders table migrated successfully")
	negotiationsTable := `
	CREATE TABLE IF NOT EXISTS negotiations (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		crop_id INTEGER NOT NULL,
		buyer_id INTEGER NOT NULL,
		farmer_id INTEGER NOT NULL,
		quantity DOUBLE PRECISION NOT NULL,
		status TEXT NOT NULL,
		round_count INTEGER NOT NULL DEFAULT 0,
		max_rounds INTEGER NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		expires_at TIMESTAMP,

		CONSTRAINT fk_negotiations_crop
			FOREIGN KEY (crop_id)
			REFERENCES crops(id),

		CONSTRAINT fk_negotiations_buyer
			FOREIGN KEY (buyer_id)
			REFERENCES farmers(id),

		CONSTRAINT fk_negotiations_farmer
			FOREIGN KEY (farmer_id)
			REFERENCES farmers(id)
	);
`

	_, err = db.Exec(negotiationsTable)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiations table migrated successfully")
	negotiationMessagesTable := `
	CREATE TABLE IF NOT EXISTS negotiation_messages (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		negotiation_id INTEGER NOT NULL,
		sender_id INTEGER NOT NULL,
		offer_price DOUBLE PRECISION NOT NULL,
		message TEXT NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

		CONSTRAINT fk_messages_negotiation
			FOREIGN KEY (negotiation_id)
			REFERENCES negotiations(id)
			ON DELETE CASCADE,

		CONSTRAINT fk_messages_sender
			FOREIGN KEY (sender_id)
			REFERENCES farmers(id)
	);
`

	_, err = db.Exec(negotiationMessagesTable)
	if err != nil {
		return err
	}

	log.Println("✅ Negotiation messages table migrated successfully")

	return nil
}
